SUPESC-227: Extended the Crefopay limit for order ID on the creation process.
spryker-eco/crefo-pay-api pull request #4
Opened 2021-09-06 11:26 UTC by herasimenko1987

- Ticket: https://spryker.atlassian.net/browse/SUPESC-227

- Release Group: https://release.spryker.com/release-groups/view/3333

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   CrefoPay              | patch                 |                       |

-----------------------------------------

#### Module CrefoPayApi

##### Change log

Fixes

-

2021-09-08 14:30 UTC, michbeck approved these changes

2021-09-08 14:58 UTC, AsonUnique approved these changes
Please, check also that all constants in this module have a dockblock according to Mark's recent message:

> Please always add docblocks for your constants as @var type  from now on. It will soon report them as missing otherwise.

2021-10-18 14:33 UTC, dmytro-sokolovskyi commented on composer.json
> +        "psr/http-message": "^1.0.0",
Looks like a major changes.
Is it really new dependency? Why we add it?

2021-10-18 14:35 UTC, dmytro-sokolovskyi commented
Fix the change log, please:
- Use `Fixes` instead of `Improvements`
- Remove this `Added GitHub Actions.`

2021-10-18 14:41 UTC, dmytro-sokolovskyi commented on composer.json
>          "spryker/kernel": "^3.0.0",
Maybe you should use `"spryker/kernel": "^3.30.0"` as in **CrefoPay** module

1 min constraint issues: Kernel constraint >= 3.30.0 expected for module CrefoPayApi (found ^3.0.0) to safely use container setters.

2021-10-19 11:08 UTC, herasimenko1987 commented on composer.json
> +        "psr/http-message": "^1.0.0",
It is used in CrefoPayApiGuzzleHttpClientAdapter.

2021-10-20 08:07 UTC, dmytro-sokolovskyi approved these changes

2021-10-25 12:44 UTC, floriankraemer requested changes
There is only one thing that concerns me, everything else is just code checker nick-picking. Please check that the latest sniffer is used, which means `dev-master`. This is what @dereuromark told me.

2021-10-25 12:44 UTC, floriankraemer commented on src/SprykerEco/Service/CrefoPayApi/HashCalculator/MacHashCalculator.php
>      protected const HASHING_ALGORITHM = 'sha1';
This has not been changed but do we really keep using SHA1 here? Can we change this to something more secure?

> Since 2005, SHA-1 has not been considered secure against well-funded opponents; as of 2010 many organizations have recommended its replacement. NIST formally deprecated use of SHA-1 in 2011 and disallowed its use for digital signatures in 2013. As of 2020, chosen-prefix attacks against SHA-1 are practical.

https://en.wikipedia.org/wiki/SHA-1

2021-10-25 12:44 UTC, floriankraemer commented on src/SprykerEco/Shared/CrefoPayApi/CrefoPayApiConstants.php
> +     * @var string
I checked this with @dereuromark there should be an empty line between @api and @var. For some reason the sniffer didn't detect it.

```suggestion
     * @api
     *
     * @var string
```

I reported it [here ](https://github.com/spryker/code-sniffer/issues/285)as discussed with @dereuromark.

2021-10-25 12:44 UTC, floriankraemer commented on src/SprykerEco/Zed/CrefoPayApi/Business/Request/CrefoPayApiRequestFields.php
> +    /**
Shouldn't there be a new line between the const and the next doc block? This applies to all the consts in this file.

2021-10-25 12:44 UTC, floriankraemer commented on src/SprykerEco/Zed/CrefoPayApi/Business/Response/Converter/CrefoPayApiResponseConverter.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on src/SprykerEco/Zed/CrefoPayApi/Business/Response/Validator/CrefoPayApiResponseValidator.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on src/SprykerEco/Zed/CrefoPayApi/Dependency/External/Guzzle/CrefoPayApiGuzzleHttpClientAdapter.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/CancelApiCallFacadeTest.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/CaptureApiCallFacadeTest.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/CreateTransactionApiCallFacadeTest.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/FinishApiCallFacadeTest.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/RefundApiCallFacadeTest.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/ReserveApiCallFacadeTest.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/_support/Business/CrefoPayApiFacadeBaseTest.php
> +    /**
New line between the doc block and const.

2021-10-25 12:44 UTC, floriankraemer commented on tests/SprykerEcoTest/Zed/CrefoPayApi/_support/CrefoPayApiZedTester.php
> +    /**
New line between the doc block and const.

2021-10-27 20:18 UTC, herasimenko1987 commented on src/SprykerEco/Service/CrefoPayApi/HashCalculator/MacHashCalculator.php
>      protected const HASHING_ALGORITHM = 'sha1';
I think sha1 is required by CrefoPay https://docs.crefopay.de/api/?php#mac-calculation

2021-10-27 20:23 UTC, dereuromark commented
Invalid changelog

Added phpstan/phpstan module to dependencies.
Added spryker/code-sniffer module to dependencies.

Please never add require-dev or test topics to changelogs

2021-10-28 12:36 UTC, dereuromark commented
The changelog is still wrong. 
The only Info so far in there is not relevant to anyone, and does not explain why this release is needed or useful

2021-10-29 09:21 UTC, floriankraemer approved these changes

2021-12-08 07:37 UTC, abitskil approved these changes

2022-02-17 07:59 UTC, DmitryLymarenko commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/CaptureApiCallFacadeTest.php
> +     * @var array
```suggestion
     * @var array<string, string>
```

2022-02-17 07:59 UTC, DmitryLymarenko commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/CreateTransactionApiCallFacadeTest.php
> +     * @var array
```suggestion
     * @var array<string, string>
```

2022-02-17 07:59 UTC, DmitryLymarenko commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/FinishApiCallFacadeTest.php
> +     * @var array
```suggestion
     * @var array<string, string>
```

2022-02-17 07:59 UTC, DmitryLymarenko commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/RefundApiCallFacadeTest.php
> +     * @var array
```suggestion
     * @var array<string, string>
```

2022-02-17 07:59 UTC, DmitryLymarenko commented on tests/SprykerEcoTest/Zed/CrefoPayApi/Business/ReserveApiCallFacadeTest.php
> +     * @var array
```suggestion
     * @var array<string, string>
```

2022-02-17 08:02 UTC, DmitryLymarenko commented
changelog section should be named `Adjustments`

2022-02-23 12:27 UTC, DmitryLymarenko approved these changes

2022-03-23 14:25 UTC, DmitryLymarenko approved these changes

2022-03-23 14:30 UTC, DmitryLymarenko requested changes
changelogs are wrong 
at least at `added missing size`...

2022-03-23 15:28 UTC, DmitryLymarenko approved these changes

2022-04-12 16:26 UTC, merged